# Generated by Django 4.1.7 on 2023-03-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(max_length=50)),
                ('JobLocationCity', models.CharField(max_length=50)),
                ('obLocationPostal', models.IntegerField()),
                ('CompanyName', models.CharField(max_length=50)),
            ],
        ),
    ]
